services:
  db:
    build: ./db
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json

  fastapi_app:
    build:
      context: .
      dockerfile: ./fastapi_app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
    volumes:
      - .:/app  # Montuje cały projekt do /app
    working_dir: /app/fastapi_app  # Wymusza na kontenerze start z tego podkatalogu
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data: